#!/bin/bash
/opt/bitnami/spark/bin/spark-submit \
 --master spark://spark-master:7077 \
 --packages org.postgresql:postgresql:42.7.3 \
 --conf spark.executorEnv.WEATHER_API_KEY=$WEATHER_API_KEY \
 --conf spark.driverEnv.WEATHER_API_KEY=$WEATHER_API_KEY \
 /opt/spark-app/weather_transform.py
